from .analysis import (
    AssetAnalysis,
    CompareResponse,
    DecisionBlock,
    FairPriceBlock,
    PricePoint,
    TechnicalBlock,
)
from .benchmark import BenchmarkPoint, BenchmarkResponse
from .dashboard import (
    Alert,
    CategoryAllocation,
    DashboardResponse,
    DashboardSummary,
    DataFreshness,
    PortfolioHealth,
)
from .dip import (
    DipAnalysisResponse,
    DipScanItem,
    DipScannerResponse,
    DipScoreBreakdownSchema,
    NewsItemSchema,
)
from .enums import (
    AssetCategory,
    AssetType,
    Liquidez,
    OptimizationStrategy,
    RendaFixaType,
    RiskProfile,
    TaxType,
)
from .goal import Goal, GoalsRequest, SectorGoal, SectorGoalsRequest
from .opportunity import OpportunitiesResponse, Opportunity
from .portfolio import (
    ClosedTrade,
    ClosedTradesResponse,
    PortfolioEvaluationRequest,
    PortfolioEvaluationResponse,
    PortfolioItem,
    PortfolioPosition,
    PortfolioSnapshot,
    PortfolioStateResponse,
    SavePortfolioRequest,
    SellRequest,
    StoredPortfolioItem,
    TaxLossCategoryBalance,
)
from .preferences import Preferences, PreferencesRequest
from .projection import (
    PassiveIncomeMonth,
    PassiveIncomeProjectionRequest,
    PassiveIncomeProjectionResponse,
)
from .quick_invest import (
    QuickInvestAllocation,
    QuickInvestRequest,
    QuickInvestResponse,
)
from .renda_fixa import (
    FixedIncomeCreateRequest,
    FixedIncomeListResponse,
    FixedIncomePosition,
    FixedIncomeUpdateRequest,
    ReferenceRates,
    RendaFixaAnalysisResult,
    RendaFixaAsset,
    RendaFixaCompareRequest,
    RendaFixaCompareResponse,
)
from .whats_new import WhatsNewItem, WhatsNewResponse

__all__ = [
    "AssetCategory",
    "AssetType",
    "Liquidez",
    "OptimizationStrategy",
    "RendaFixaType",
    "RiskProfile",
    "TaxType",
    "AssetAnalysis",
    "PricePoint",
    "CompareResponse",
    "DecisionBlock",
    "FairPriceBlock",
    "TechnicalBlock",
    "BenchmarkPoint",
    "BenchmarkResponse",
    "PortfolioHealth",
    "PortfolioEvaluationRequest",
    "PortfolioEvaluationResponse",
    "PortfolioItem",
    "PortfolioPosition",
    "PortfolioSnapshot",
    "PortfolioStateResponse",
    "SavePortfolioRequest",
    "StoredPortfolioItem",
    "SellRequest",
    "ClosedTrade",
    "ClosedTradesResponse",
    "TaxLossCategoryBalance",
    "Goal",
    "GoalsRequest",
    "SectorGoal",
    "SectorGoalsRequest",
    "Preferences",
    "PreferencesRequest",
    "Opportunity",
    "OpportunitiesResponse",
    "Alert",
    "CategoryAllocation",
    "DashboardResponse",
    "DashboardSummary",
    "DataFreshness",
    "DipAnalysisResponse",
    "DipScanItem",
    "DipScannerResponse",
    "DipScoreBreakdownSchema",
    "NewsItemSchema",
    "RendaFixaAsset",
    "RendaFixaAnalysisResult",
    "RendaFixaCompareRequest",
    "RendaFixaCompareResponse",
    "ReferenceRates",
    "WhatsNewItem",
    "WhatsNewResponse",
    "FixedIncomeCreateRequest",
    "FixedIncomeUpdateRequest",
    "FixedIncomePosition",
    "FixedIncomeListResponse",
    "PassiveIncomeMonth",
    "PassiveIncomeProjectionRequest",
    "PassiveIncomeProjectionResponse",
    "QuickInvestRequest",
    "QuickInvestResponse",
    "QuickInvestAllocation",
]
