import { bootstrapApplication } from '@angular/platform-browser';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { importProvidersFrom } from '@angular/core';
import {
  ArrowRight,
  Briefcase,
  ChartColumn,
  ChartPie,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleArrowDown,
  CircleArrowUp,
  CircleCheck,
  CircleMinus,
  CircleUser,
  CircleX,
  Cloud,
  Coins,
  DollarSign,
  GitCompare,
  House,
  Info,
  LayoutDashboard,
  Lightbulb,
  List,
  LoaderCircle,
  LucideAngularModule,
  Minus,
  Moon,
  Newspaper,
  Plus,
  Radar,
  RefreshCw,
  Scan,
  Search,
  Settings,
  Star,
  Sun,
  Table,
  Target,
  ThumbsDown,
  ThumbsUp,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Wallet,
  WandSparkles,
  X,
} from 'lucide-angular';
import { AppComponent } from './app/app.component';
import { httpErrorInterceptor } from './app/core/interceptors/http-error.interceptor';

bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient(withInterceptors([httpErrorInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowRight,
        Briefcase,
        ChartColumn,
        ChartPie,
        Check,
        ChevronLeft,
        ChevronRight,
        CircleAlert,
        CircleArrowDown,
        CircleArrowUp,
        CircleCheck,
        CircleMinus,
        CircleUser,
        CircleX,
        Cloud,
        Coins,
        DollarSign,
        GitCompare,
        House,
        Info,
        LayoutDashboard,
        Lightbulb,
        List,
        LoaderCircle,
        Minus,
        Moon,
        Newspaper,
        Plus,
        Radar,
        RefreshCw,
        Scan,
        Search,
        Settings,
        Star,
        Sun,
        Table,
        Target,
        ThumbsDown,
        ThumbsUp,
        TrendingDown,
        TrendingUp,
        TriangleAlert,
        Wallet,
        WandSparkles,
        X,
      }),
    ),
  ],
}).catch((err) => console.error(err));
