import { bootstrapApplication } from '@angular/platform-browser';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  PreloadAllModules,
  provideRouter,
  withComponentInputBinding,
  withPreloading,
} from '@angular/router';
import { importProvidersFrom } from '@angular/core';
import {
  ArrowRight,
  Bell,
  Bitcoin,
  Briefcase,
  Building2,
  Calculator,
  ChartBar,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleArrowDown,
  CircleArrowUp,
  CircleCheck,
  CircleQuestionMark,
  CircleMinus,
  CircleUser,
  CircleX,
  CircleDot,
  Cloud,
  Coins,
  Cpu,
  Database,
  DollarSign,
  Eye,
  Factory,
  Gem,
  GitCompare,
  Globe,
  HeartPulse,
  House,
  Inbox,
  Info,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  List,
  LoaderCircle,
  LucideAngularModule,
  Minus,
  Moon,
  Newspaper,
  Percent,
  PlugZap,
  Plus,
  Radar,
  RefreshCw,
  Scan,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Table,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Wallet,
  WandSparkles,
  Wifi,
  X,
  Zap,
} from 'lucide-angular';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { authInterceptor } from './app/core/interceptors/auth.interceptor';
import { httpErrorInterceptor } from './app/core/interceptors/http-error.interceptor';

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes, withComponentInputBinding(), withPreloading(PreloadAllModules)),
    provideHttpClient(withInterceptors([authInterceptor, httpErrorInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowRight,
        Bell,
        Bitcoin,
        Briefcase,
        Building2,
        Calculator,
        ChartBar,
        ChartColumn,
        ChartPie,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        CircleAlert,
        CircleArrowDown,
        CircleArrowUp,
        CircleCheck,
        CircleQuestionMark,
        CircleMinus,
        CircleUser,
        CircleX,
        CircleDot,
        Cloud,
        Coins,
        Cpu,
        Database,
        DollarSign,
        Eye,
        Factory,
        Gem,
        GitCompare,
        Globe,
        HeartPulse,
        House,
        Inbox,
        Info,
        Landmark,
        LayoutDashboard,
        Lightbulb,
        List,
        LoaderCircle,
        Minus,
        Moon,
        Newspaper,
        Percent,
        PlugZap,
        Plus,
        Radar,
        RefreshCw,
        Scan,
        Search,
        Settings,
        ShoppingBag,
        ShoppingCart,
        Sparkles,
        Star,
        Sun,
        Table,
        Target,
        ThumbsDown,
        ThumbsUp,
        Trash2,
        TrendingDown,
        TrendingUp,
        TriangleAlert,
        Trophy,
        Wallet,
        WandSparkles,
        Wifi,
        X,
        Zap,
      })
    ),
  ],
}).catch(err => console.error(err));
